export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum USER_ROLE {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum EVENT_STATUS {
  CANCEL = 'CANCEL',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum SEAT_STATUS {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
}
